// Shared mock data for development until DB has real cars

export const MOCK_CARS = [
  {
    id: "1",
    slug: "toyota-corolla-2023-abc",
    make: "טויוטה",
    model: "קורולה",
    year: 2023,
    price: 115000,
    originalPrice: 125000,
    km: 32000,
    hand: 1,
    fuelType: "PETROL" as const,
    transmission: "AUTOMATIC" as const,
    engineSize: 1800,
    horsepower: 140,
    color: "לבן",
    doors: 4,
    seats: 5,
    region: "CENTER" as const,
    city: "תל אביב",
    fuelConsumption: 14,
    reliability: 9,
    description: "טויוטה קורולה 2023 במצב מעולה. יד ראשונה, שמורה, ללא תאונות. טסט עד 2025. כולל מערכת מולטימדיה, מצלמת רוורס, חיישני חנייה.",
    hasFinancing: true,
    hasTradeIn: true,
    hasWarranty: true,
    categoryTag: "families",
    status: "APPROVED" as const,
    viewsCount: 342,
    clicksCount: 89,
    leadsCount: 12,
    dealerId: "dealer-1",
    dealerName: "אוטו פלוס תל אביב",
    dealerPhone: "050-1234567",
    dealerCity: "תל אביב",
    images: ["/hero-bg.png"],
    createdAt: "2024-03-15",
  },
  {
    id: "2",
    slug: "hyundai-tucson-2022-def",
    make: "יונדאי",
    model: "טוסון",
    year: 2022,
    price: 145000,
    originalPrice: null,
    km: 48000,
    hand: 1,
    fuelType: "HYBRID" as const,
    transmission: "AUTOMATIC" as const,
    engineSize: 1600,
    horsepower: 180,
    color: "שחור",
    doors: 4,
    seats: 5,
    region: "CENTER" as const,
    city: "רמת גן",
    fuelConsumption: 16,
    reliability: 8,
    description: "יונדאי טוסון היברידי 2022, מצב מצוין. מושבי עור, גג פנורמי, מערכת בטיחות מתקדמת. שמור בסוכנות.",
    hasFinancing: true,
    hasTradeIn: false,
    hasWarranty: true,
    categoryTag: "families",
    status: "APPROVED" as const,
    viewsCount: 256,
    clicksCount: 67,
    leadsCount: 8,
    dealerId: "dealer-2",
    dealerName: "מוטורס פלוס",
    dealerPhone: "050-2345678",
    dealerCity: "רמת גן",
    images: ["/hero-bg.png"],
    createdAt: "2024-03-10",
  },
  {
    id: "3",
    slug: "mazda-cx5-2023-ghi",
    make: "מאזדה",
    model: "CX-5",
    year: 2023,
    price: 165000,
    originalPrice: 175000,
    km: 25000,
    hand: 1,
    fuelType: "PETROL" as const,
    transmission: "AUTOMATIC" as const,
    engineSize: 2000,
    horsepower: 165,
    color: "אפור",
    doors: 4,
    seats: 5,
    region: "NORTH" as const,
    city: "חיפה",
    fuelConsumption: 12,
    reliability: 9,
    description: "מאזדה CX-5 2023 בגרסת היוקרה. עור מלא, חימום מושבים, מערכת BOSE, קרוז קונטרול אדפטיבי.",
    hasFinancing: true,
    hasTradeIn: true,
    hasWarranty: false,
    categoryTag: "families",
    status: "APPROVED" as const,
    viewsCount: 189,
    clicksCount: 45,
    leadsCount: 5,
    dealerId: "dealer-3",
    dealerName: "צפון אוטו",
    dealerPhone: "050-3456789",
    dealerCity: "חיפה",
    images: ["/hero-bg.png"],
    createdAt: "2024-03-08",
  },
  {
    id: "4",
    slug: "skoda-octavia-2024-jkl",
    make: "סקודה",
    model: "אוקטביה",
    year: 2024,
    price: 135000,
    originalPrice: null,
    km: 15000,
    hand: 1,
    fuelType: "PETROL" as const,
    transmission: "AUTOMATIC" as const,
    engineSize: 1500,
    horsepower: 150,
    color: "כסוף",
    doors: 4,
    seats: 5,
    region: "CENTER" as const,
    city: "פתח תקווה",
    fuelConsumption: 15,
    reliability: 8,
    description: "סקודה אוקטביה 2024 חדשה כמעט. תא מטען ענק, נוחות נסיעה מעולה, חסכונית בדלק.",
    hasFinancing: true,
    hasTradeIn: false,
    hasWarranty: true,
    categoryTag: "economical",
    status: "APPROVED" as const,
    viewsCount: 412,
    clicksCount: 98,
    leadsCount: 15,
    dealerId: "dealer-1",
    dealerName: "אוטו פלוס תל אביב",
    dealerPhone: "050-1234567",
    dealerCity: "פתח תקווה",
    images: ["/hero-bg.png"],
    createdAt: "2024-03-20",
  },
  {
    id: "5",
    slug: "kia-picanto-2023-mno",
    make: "קיה",
    model: "פיקנטו",
    year: 2023,
    price: 65000,
    originalPrice: 72000,
    km: 20000,
    hand: 1,
    fuelType: "PETROL" as const,
    transmission: "AUTOMATIC" as const,
    engineSize: 1000,
    horsepower: 67,
    color: "אדום",
    doors: 4,
    seats: 5,
    region: "TEL_AVIV" as const,
    city: "תל אביב",
    fuelConsumption: 18,
    reliability: 8,
    description: "קיה פיקנטו 2023, מושלמת לסטודנטים ולנסיעות בעיר. חסכונית, קלה לחנייה, עם כל האבזור.",
    hasFinancing: true,
    hasTradeIn: false,
    hasWarranty: false,
    categoryTag: "students",
    status: "APPROVED" as const,
    viewsCount: 567,
    clicksCount: 134,
    leadsCount: 22,
    dealerId: "dealer-4",
    dealerName: "דיל אוטו",
    dealerPhone: "050-4567890",
    dealerCity: "תל אביב",
    images: ["/hero-bg.png"],
    createdAt: "2024-03-12",
  },
  {
    id: "6",
    slug: "bmw-x3-2022-pqr",
    make: "ב.מ.וו",
    model: "X3",
    year: 2022,
    price: 220000,
    originalPrice: 250000,
    km: 40000,
    hand: 1,
    fuelType: "PETROL" as const,
    transmission: "AUTOMATIC" as const,
    engineSize: 2000,
    horsepower: 184,
    color: "שחור",
    doors: 4,
    seats: 5,
    region: "CENTER" as const,
    city: "הרצליה",
    fuelConsumption: 11,
    reliability: 7,
    description: "BMW X3 2022 בגרסת M Sport. מלא אופציות, גג פנורמי, הנעה כפולה, מערכת ניווט מקצועית.",
    hasFinancing: true,
    hasTradeIn: true,
    hasWarranty: true,
    categoryTag: "luxury",
    status: "APPROVED" as const,
    viewsCount: 723,
    clicksCount: 201,
    leadsCount: 18,
    dealerId: "dealer-5",
    dealerName: "פרימיום מוטורס",
    dealerPhone: "050-5678901",
    dealerCity: "הרצליה",
    images: ["/hero-bg.png"],
    createdAt: "2024-03-05",
  },
  {
    id: "7",
    slug: "suzuki-vitara-2023-stu",
    make: "סוזוקי",
    model: "ויטרה",
    year: 2023,
    price: 125000,
    originalPrice: null,
    km: 18000,
    hand: 1,
    fuelType: "HYBRID" as const,
    transmission: "AUTOMATIC" as const,
    engineSize: 1400,
    horsepower: 129,
    color: "לבן",
    doors: 4,
    seats: 5,
    region: "SOUTH" as const,
    city: "באר שבע",
    fuelConsumption: 17,
    reliability: 8,
    description: "סוזוקי ויטרה היברידית 2023. חסכונית, רחבה, מתאימה למשפחות. הנעה כפולה.",
    hasFinancing: false,
    hasTradeIn: true,
    hasWarranty: true,
    categoryTag: "families",
    status: "APPROVED" as const,
    viewsCount: 298,
    clicksCount: 76,
    leadsCount: 9,
    dealerId: "dealer-6",
    dealerName: "דרום אוטו",
    dealerPhone: "050-6789012",
    dealerCity: "באר שבע",
    images: ["/hero-bg.png"],
    createdAt: "2024-03-18",
  },
  {
    id: "8",
    slug: "tesla-model3-2023-vwx",
    make: "טסלה",
    model: "Model 3",
    year: 2023,
    price: 175000,
    originalPrice: 195000,
    km: 22000,
    hand: 1,
    fuelType: "ELECTRIC" as const,
    transmission: "AUTOMATIC" as const,
    engineSize: 0,
    horsepower: 283,
    color: "לבן",
    doors: 4,
    seats: 5,
    region: "TEL_AVIV" as const,
    city: "תל אביב",
    fuelConsumption: 0,
    reliability: 8,
    description: "טסלה Model 3 2023 Long Range. אוטופיילוט, טווח 600 ק\"מ, טעינה מהירה, מסך 15 אינץ'.",
    hasFinancing: true,
    hasTradeIn: true,
    hasWarranty: true,
    categoryTag: "luxury",
    status: "APPROVED" as const,
    viewsCount: 890,
    clicksCount: 245,
    leadsCount: 30,
    dealerId: "dealer-5",
    dealerName: "פרימיום מוטורס",
    dealerPhone: "050-5678901",
    dealerCity: "תל אביב",
    images: ["/hero-bg.png"],
    createdAt: "2024-03-22",
  },
  {
    id: "9",
    slug: "toyota-yaris-2022-yza",
    make: "טויוטה",
    model: "יאריס",
    year: 2022,
    price: 78000,
    originalPrice: null,
    km: 35000,
    hand: 2,
    fuelType: "PETROL" as const,
    transmission: "AUTOMATIC" as const,
    engineSize: 1500,
    horsepower: 120,
    color: "כחול",
    doors: 4,
    seats: 5,
    region: "JERUSALEM" as const,
    city: "ירושלים",
    fuelConsumption: 17,
    reliability: 9,
    description: "טויוטה יאריס 2022, יד שנייה שמורה. חסכונית מאוד, אמינה, מצב מכני מעולה.",
    hasFinancing: true,
    hasTradeIn: false,
    hasWarranty: false,
    categoryTag: "students",
    status: "APPROVED" as const,
    viewsCount: 445,
    clicksCount: 112,
    leadsCount: 14,
    dealerId: "dealer-7",
    dealerName: "ירושלים מוטורס",
    dealerPhone: "050-7890123",
    dealerCity: "ירושלים",
    images: ["/hero-bg.png"],
    createdAt: "2024-03-01",
  },
  {
    id: "10",
    slug: "mitsubishi-outlander-2023-bcd",
    make: "מיצובישי",
    model: "אאוטלנדר",
    year: 2023,
    price: 185000,
    originalPrice: null,
    km: 30000,
    hand: 1,
    fuelType: "HYBRID" as const,
    transmission: "AUTOMATIC" as const,
    engineSize: 2400,
    horsepower: 224,
    color: "אפור",
    doors: 4,
    seats: 7,
    region: "HAIFA" as const,
    city: "חיפה",
    fuelConsumption: 13,
    reliability: 7,
    description: "מיצובישי אאוטלנדר PHEV 2023. 7 מקומות, היברידי נטען, הנעה כפולה. מושלם למשפחות גדולות.",
    hasFinancing: true,
    hasTradeIn: true,
    hasWarranty: true,
    categoryTag: "large-families",
    status: "APPROVED" as const,
    viewsCount: 334,
    clicksCount: 87,
    leadsCount: 11,
    dealerId: "dealer-3",
    dealerName: "צפון אוטו",
    dealerPhone: "050-3456789",
    dealerCity: "חיפה",
    images: ["/hero-bg.png"],
    createdAt: "2024-03-14",
  },
];

export type MockCar = (typeof MOCK_CARS)[number];
